### ISSUE TITLE
Addon missing icon

### ISSUE THREAD

**Issue by lusum** [ampache/ampache-xbmc-plugin#1]
Should be useful to have an addon icon, it is mandatory for the inclusion in the main kodi repository

**Comment by lachlan-00** [comment]
svg or in a specific size?

**Comment by lachlan-00** [comment]
Now that this is official you could use the ampache logos. dark/light theme images.
![ampache-dark](https://user-images.githubusercontent.com/1305249/72761416-a94cdf80-3c27-11ea-9717-453bd6dfc98f.png)
![ampache-light](https://user-images.githubusercontent.com/1305249/72761417-a94cdf80-3c27-11ea-9bdf-b18d80744663.png)

**Comment by lachlan-00** [comment]
Your choice (but i think the blue one)

I just had a look at the icon size and these are 256x256 which matches with the images on the addons page.

**Comment by lusum** [comment]
ok, i will commit the blue one

**Comment by lusum** [comment]
The add-on rules requires a fanart ( any idea ) and the translation of all strrings ( i will subscribe to transifex to start that ), maybe in the future it will be possible to submit this plugin to the official kodi repository.

**Comment by lachlan-00** [comment]
I think I can make up something like the soundcloud one for fanart using the colours from ampache.org's theme.
https://github.com/jaylinski/kodi-addon-soundcloud/blob/master/resources/fanart.jpg

Does 18.x support python3 as well? if so then it's a good time to start that. I really enjoy python so i can start making pulls when I get to installing 19.

Transifex is a good idea, I think a lot of our current translators would probably help and we can advertise it on the Ampache transifex page/twitter/mastodon/etc.

**Comment by lusum** [comment]
>Fanart

Ok, i will try

>Does 18.x support python3 as well?

I don't know, really, i think i will work on python3 porting in the future

>Transifex is a good idea, I think a lot of our current translators would probably help and we can advertise it on the Ampache transifex page/twitter/mastodon/etc.

I will use it in the future,  i think, now i prefet to focus on overall stability of the plugin and fixing some glitches.

**Comment by lusum** [comment]
This fanart is ok or i need a different background color?

![fanart](https://user-images.githubusercontent.com/541595/73122780-9bc58b80-3f80-11ea-8e1e-54a44e619e55.jpg)

**Comment by lachlan-00** [comment]
No, I like that a lot!

**Comment by lusum** [comment]
ok, i have committed the files and i close the issue.
