### ISSUE TITLE
 [Feature Request] Add support for Smart Playlists

### ISSUE THREAD

**Issue by xekon** [ampache/ampache-xbmc-plugin#12]
When I asked about Smart Playlists, you said you already planned on adding support for them later.

I am submitting this feature request formally, and so that I can be one of your first testers if you need any testers.

Thank you for this plugin, it is awesome!

**Comment by lusum** [comment]
Now, i will do a feature freeze in 1.2 series and i will submit the stable 1.2.2. I will do a major rewrite in 2.0 branch, but i will wait to commit until it will be usable. When the rewrite will take place, i would add easly new features.

**Comment by xekon** [comment]
Awesome, very exciting! Looking forward to it, and happy to test when it becomes available.

**Comment by lusum** [comment]
Support added in 2.0 branch

**Comment by xekon** [comment]
I just tested it! Very Awesome, thank you!
