### ISSUE TITLE
2.0 branch works on Kodi 18.9 under Ubuntu but does not work on OSMC (Kodi 18.9)

### ISSUE THREAD

**Issue by xekon** [ampache/ampache-xbmc-plugin#13]
On my Raspberry Pi running OSMC I previously had the plugin installed from: https://github.com/ampache/ampache-xbmc-plugin/tree/ampache-leia

ampache-leia installed without issues on the raspberry pi.

Today I tried to install the new 2.0 Branch on the raspberry pi OSMC and got an error: `Failed due to an invalid structure`

I checked the installed version of kodi on OSMC:

```
/home/osmc$ grep Kodi .kodi/temp/kodi.log | head -3
2020-12-07 08:18:10.177 T:1916335024  NOTICE: Starting Kodi (18.9). Platform: Linux ARM (Thumb) 32-bit
2020-12-07 08:18:10.177 T:1916335024  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
2020-12-07 08:18:10.177 T:1916335024  NOTICE: Kodi compiled 2020-11-26 by GCC 8.3.0 for Linux ARM (Thumb) 32-bit version 4.19.152 (267160)
```

The new 2.0 branch works without issue on both of my Ubuntu Desktops

I am hoping that since ampache-leia worked on the raspberry pi that your new 2.0 branch can also work on the raspberry pi.

I apologize for not providing a kodi log right now, if it is needed then please let me know. The raspberry pi is located at my work office so I wont be able to get that until this Saturday.

**Comment by lusum** [comment]
I had the same problem with my raspberry, try to reboot the device or to uninstall previous version and reinstall.

**Comment by xekon** [comment]
Thanks! I will give that a try this Saturday :+1:

**Comment by lusum** [comment]
Can you tell me if this bug is closed or not?

**Comment by xekon** [comment]
@lusum I am going into work today and plan to test it there today.
