### ISSUE TITLE
Change Order Ascending / Descending not working, not for podcasts or albums.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache-xbmc-plugin#15]
While using the ampache-xbmc-plugin I wanted to change the order of the results.

In the case of podcasts it puts the newest episode first, this is fine if your just listening to only the last episode, but if you wanted to listen to the 10 latest episodes in order then you cannot, you can only listen to them backwards.

![2021-02-19_14-54](https://user-images.githubusercontent.com/106644/108570538-069be000-72c3-11eb-93f6-21420e0e5faf.png)

**Comment by lusum** [comment]
When they will release the 4.4.0 i will start to test, now, i have to work in a blind way..

**Comment by lusum** [comment]
Added for podcasts, not added to songs ( random playlists becoming a mess ) , not so sure for albums ( sort by name? year?  )

**Comment by xekon** [comment]
I got the chance to to install this and try it out today, very awesome! thank you.

**Comment by lusum** [comment]
You can do this simply clicking random order in kodi commands.
