### ISSUE TITLE
[Feature Request] New Setting, Pressing Play on a song automatically enters full screen mode.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache-xbmc-plugin#17]
Currently if you play a song, you have to open the side menu and select the box to enter full screen mode.

I would like it if there were a setting for the plugin that I could set it to automatically enter full screen mode when I play a song.

This shows a nice full screen picture for the currently playing song, it also makes the image change anytime the song changes.

This is also good for preventing screen burn in.

Another idea for a secondary feature would be show the information panel for 10 seconds or so when the song changes, then hide the information. (not sure how difficult this one would be, but it would give a way to see the song name for a short while when the song changes, without having to leave the song info on screen the whole time.)

**Comment by lusum** [comment]
I really don't know if this is possible, not, i think this is impossible to do in the plugin, cause the plugin have no control on player ( and cannot by kodi's rules ). I have to pass the url of the song to 

>xbmcplugin.setResolvedUrl(handle=int(sys.argv[1]), succeeded=True,listitem=liz)

setResolvedUrl and all the play stuff is handled by kodi ( even the gapless play, i cannot control it ). So the plugin create a nice list of songs ( albums/artists ) and give all the possible information to kodi, when we play the track kodi reads the list and all the informations passed and handles them. 

see that : 

_Originally posted by @enen92 in https://github.com/xbmc/repo-plugins/pull/3328#discussion_r564064325_

>please use setResolvedUrl, plugins are not allowed to call Player.play directly

**Comment by lusum** [comment]
The first part is possible

**Comment by xekon** [comment]
Awesome! Just installed and tested it, works great! Thank You @lusum !

**Comment by lusum** [comment]
Btw with kodi 19 your second request is by default

**Comment by xekon** [comment]
I just noticed that! very cool :)
