### ISSUE TITLE
put version support in the release page

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampache-xbmc-plugin#2]
Details of what versions of Kodi and Ampache are/aren't supported would help a few people understand what they need to use

https://www.reddit.com/r/ampache/comments/euxx89/if_you_use_kodi_make_sure_you_check_out_our/fft9xb7?utm_medium=android_app&utm_source=share

**Comment by lusum** [comment]
This plugin support ampache from 350001 to the newest, nextcloud music uses an older ampache api version, so i support also the older one
