### ISSUE TITLE
The albums are empty

### ISSUE THREAD

**Issue by christophe195** [ampache/ampache-xbmc-plugin#24]
Hello,

I have linked a nextcloud music ampache service to kodi, when i try to play music it works but when i open an album the content is empty. Is this comment?

Greathings

**Comment by lusum** [comment]
I have tested with nextcloud and all seems fine. ( sometimes nextcloud music developer post here if he sees some problem ). Can you turn on the debug and post the logs?

**Comment by lusum** [comment]
open this issue on nextcloud music [#6](https://github.com/paulijar/music/issues/6)

**Comment by lusum** [comment]
[Fixed on onwcloud/music](https://github.com/owncloud/music/issues/934)

**Comment by christophe195** [comment]
Realy thansk for fixing this
