### ISSUE TITLE
Kodi 18.6 Ampache error

### ISSUE THREAD

**Issue by MB7708** [ampache/ampache-xbmc-plugin#3]
Hello everyone,
I installed the plug in on three different platforms (RaspberryPi4, Sony Brava TV, Samsung Tab S2) 
on which Kodi 18.6 runs. As soon as I want to fill out the server settings I get the error Ampache error.
Can someone take a look at that?

![20200321_170739](https://user-images.githubusercontent.com/60877675/77251450-b2215800-6c4e-11ea-97d6-c7574bdce9b4.jpg)

Thank you

**Comment by lusum** [comment]
Yes, is a bug and i have tested it, i will fix and i will release a new version.

**Comment by lusum** [comment]
The bug was serious and has been fixed in the new 1.0.2 version, along a couple of other minor bugs. The 1.0.2 version has been released.

**Comment by MB7708** [comment]
Thanks for the quick response. Now it works fine on all platforms. The plugin is great and makes fun. Thanks for that.

**Comment by lusum** [comment]
Thanks
