### ISSUE TITLE
The 'stats' action is called with an invalid filter "hightest"

### ISSUE THREAD

**Issue by paulijar** [ampache/ampache-xbmc-plugin#4]
The Kodi Ampache plugin UI has a recurring typo where word "hightest" is used when probably "highest" has been intended:
![image](https://user-images.githubusercontent.com/8565946/92302958-4ff8ad00-ef79-11ea-84cc-3bad44baa254.png)

The same typo is present also in the Ampache API calls, when the action `stats` is called with argument `filter=hightest`. I assume that this doesn't return you any results from the Ampache server, or at least not the ones you expected. I don't actually have Ampache server installed, but looking at the API documentation and the source codes of Ampache, there's no such typo on that side.

PS. I'm the author of the Nextcloud/ownCloud Music app. In case you find anything off in my server implementation, please let me know. Obviously, the Music app does not cover 100% of the Ampache API and probably never will. But I'm in the process of gradually improving the API coverage, and I'd like to concentrate on those parts of the API which are actually being used by the clients.

**Comment by lusum** [comment]
English is not my first language, so, this is indeed an error. I will fix it and i will release a new version soon, after some tests.

**Comment by lusum** [comment]
Yes, one little problem with nextcloud, your plugin use username/password, but the explicatio seems quite confused

>Here you can generate passwords to use with the Ampache or Subsonic API. Separate passwords are used because they can't be stored in a really secure way due to the design of the APIs. You can generate as many passwords as you want and revoke them at anytime.

It seems a sort of api-key, maybe a better explication should be possible?

**Comment by paulijar** [comment]
> It seems a sort of api-key, maybe a better explication should be possible?

Well, yes, it is kind of an API key. On the other hand, it should be entered in the client-end to a field which is usually labeled "password", so calling it a "password" is probably less confusing. Ampache has added their own API key mechanism as an alternative authentication system in the API v400001, and this is not yet supported in the Music app.

I don't want to have too long descriptive text on the application UI for this, but I'll consider adding a link to a more complete explanation.

**Comment by lusum** [comment]
Thanks, i have fixed the bug and i will commit soon ( i have some tests to do in before )
