### ISSUE TITLE
Artist list missing artist image, only albums are showing images.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache-xbmc-plugin#8]
Ampache is able to display both artist and album images: https://github.com/ampache/ampache/issues/2304

here is my directory structure:

/audio/genre/artist/artist.jpg
/audio/genre/artist/Year - Album/folder.jpg
/audio/genre/artist/Year - Album/01 - The First Song.mp3
/audio/genre/artist/Year - Album/02 - The Second Song.mp3

It would be great if the artist images were displayed while browsing artists :)

Kodi Version: 18.9.0
Ampache Version: Latest Ampache Develop

**Comment by lusum** [comment]
I will work to a solution, i think it is possibile, but it is needed a partial rework of image cache

**Comment by lusum** [comment]
Added in develop branch, it will published in the next release

**Comment by xekon** [comment]
@lusum  Previously when I browsed Library > Albums Those would display images. But the artists never did.

Now neither Albums OR Artists are displaying images.

**Comment by lusum** [comment]
this is added in develop branch, not in master

**Comment by xekon** [comment]
@lusum I enabled the setting for images in long lists. When I had version 1.2.0 I was seeing images for albums, now I am not with version 1.2.1.

Today I installed version develop of the plugin: https://github.com/ampache/ampache-xbmc-plugin/tree/develop

I now have images for Artists which is GREAT! thanks for that! However I no longer have images for albums:

Artist image:

![2021-02-01_13-46](https://user-images.githubusercontent.com/106644/106522023-f0ed8480-6493-11eb-9c24-4a4dcb8a8812.png)

Missing Album image:

![2021-02-01_13-48](https://user-images.githubusercontent.com/106644/106522186-24c8aa00-6494-11eb-8a50-c46c5def8f17.png)

**Comment by lusum** [comment]
In all my version album art works, i have not touched the album art part of the code, only the artist lists, so it seems strange to me. Please try another time, maybe wait a moment, kodi on some devices like raspberry pi is quite slow.

**Comment by xekon** [comment]
@lusum both of my two test machines exhibit this problem, what type of systems are you running that do not have the problem?

my systems:

system 1:  Ubuntu 18.04, Kodi 18.9, Ampache Develop 5.0, ampache-xbmc-plugin-leia

system 2:  Ubuntu 20.04, Kodi 18.9, Ampache Develop 5.0, ampache-xbmc-plugin-leia

The two things I have not tried are using Kodi 19+ or using Ampache stable instead of Develop 5.0

I am not sure if I can move from using Ampache develop to ampache stable without some way to downgrade my ampache database, but I could install it as a test at the very least.

Getting Kodi 19+ installed probably wont be too difficult, but I am hoping it gets officially released soon because I have had issues with beta and prerelease version of kodi in the past.

**Comment by lusum** [comment]
This is really strange, can you can see the content of the folder .kodi/userdata/addon_data/plugin.audio.ampache ? The images are in the folder media/cache/ that is divided in the folders artist, album and song. You can find the album images in album folder. 

Second thing: uncomment the xbmc.log lines in art.py to have a more complete understanding. The module is cacheart.

**Comment by xekon** [comment]
I am now using ampache stable instead of ampache develop and now both artist and album images are working.

https://github.com/ampache/ampache/tree/master
https://github.com/ampache/ampache-xbmc-plugin/tree/ampache-leia

Thank you :)
